//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vote.Controls {
    
    
    public partial class ManagePoliticiansPanel {
        
        /// <summary>
        /// ManagePoliticiansPanelMode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden ManagePoliticiansPanelMode;
        
        /// <summary>
        /// CandidateControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl CandidateControl;
        
        /// <summary>
        /// IncumbentCountMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl IncumbentCountMessage;
        
        /// <summary>
        /// ManagePoliticiansMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ManagePoliticiansMessage;
        
        /// <summary>
        /// IncumbentCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden IncumbentCount;
        
        /// <summary>
        /// ControlAddCandidatesCandidateListValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden ControlAddCandidatesCandidateListValue;
        
        /// <summary>
        /// ControlAddCandidatesCandidateList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ControlAddCandidatesCandidateList;
        
        /// <summary>
        /// AsteriskAddCandidatesCandidateList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl AsteriskAddCandidatesCandidateList;
        
        /// <summary>
        /// FindPolitician control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vote.Controls.FindPolitician FindPolitician;
        
        /// <summary>
        /// AddExistingCandidateButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputButton AddExistingCandidateButton;
        
        /// <summary>
        /// ConsolidatePoliticiansButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputButton ConsolidatePoliticiansButton;
        
        /// <summary>
        /// UpdatePanelAddNewCandidate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel UpdatePanelAddNewCandidate;
        
        /// <summary>
        /// ContainerAddNewCandidate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ContainerAddNewCandidate;
        
        /// <summary>
        /// AddCandidateValidateDuplicates control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden AddCandidateValidateDuplicates;
        
        /// <summary>
        /// AddCandidateMainIdIfRunningMate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden AddCandidateMainIdIfRunningMate;
        
        /// <summary>
        /// AddCandidateFormattedName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden AddCandidateFormattedName;
        
        /// <summary>
        /// AddCandidateStateName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden AddCandidateStateName;
        
        /// <summary>
        /// AddCandidateNewId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden AddCandidateNewId;
        
        /// <summary>
        /// AddCandidateDuplicatesHtml control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl AddCandidateDuplicatesHtml;
        
        /// <summary>
        /// ControlAddNewCandidateFName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vote.TextBoxWithNormalizedLineBreaks ControlAddNewCandidateFName;
        
        /// <summary>
        /// ControlAddNewCandidateMName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vote.TextBoxWithNormalizedLineBreaks ControlAddNewCandidateMName;
        
        /// <summary>
        /// ControlAddNewCandidateNickname control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vote.TextBoxWithNormalizedLineBreaks ControlAddNewCandidateNickname;
        
        /// <summary>
        /// ControlAddNewCandidateLName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vote.TextBoxWithNormalizedLineBreaks ControlAddNewCandidateLName;
        
        /// <summary>
        /// ControlAddNewCandidateSuffix control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vote.TextBoxWithNormalizedLineBreaks ControlAddNewCandidateSuffix;
        
        /// <summary>
        /// ControlAddNewCandidateStateCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ControlAddNewCandidateStateCode;
        
        /// <summary>
        /// AddNewCandidateOpenEditPanelCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox AddNewCandidateOpenEditPanelCheckBox;
        
        /// <summary>
        /// FeedbackAddNewCandidate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vote.Controls.FeedbackContainerControl FeedbackAddNewCandidate;
        
        /// <summary>
        /// ButtonAddNewCandidate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ButtonAddNewCandidate;
        
        /// <summary>
        /// AddNewCandidateButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputButton AddNewCandidateButton;
        
        /// <summary>
        /// UpdatePanelEditPolitician control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel UpdatePanelEditPolitician;
        
        /// <summary>
        /// ContainerEditPolitician control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ContainerEditPolitician;
        
        /// <summary>
        /// EditPoliticianReloading control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden EditPoliticianReloading;
        
        /// <summary>
        /// CandidateToEdit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden CandidateToEdit;
        
        /// <summary>
        /// CandidateToEditIncumbent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden CandidateToEditIncumbent;
        
        /// <summary>
        /// MainCandidateIfRunningMate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden MainCandidateIfRunningMate;
        
        /// <summary>
        /// CandidateHtml control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl CandidateHtml;
        
        /// <summary>
        /// UndoEditPolitician control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl UndoEditPolitician;
        
        /// <summary>
        /// EditPoliticianTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl EditPoliticianTitle;
        
        /// <summary>
        /// NameOnBallots control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl NameOnBallots;
        
        /// <summary>
        /// ControlEditPoliticianFName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vote.TextBoxWithNormalizedLineBreaks ControlEditPoliticianFName;
        
        /// <summary>
        /// AsteriskEditPoliticianFName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl AsteriskEditPoliticianFName;
        
        /// <summary>
        /// ControlEditPoliticianMName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vote.TextBoxWithNormalizedLineBreaks ControlEditPoliticianMName;
        
        /// <summary>
        /// AsteriskEditPoliticianMName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl AsteriskEditPoliticianMName;
        
        /// <summary>
        /// ControlEditPoliticianNickname control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vote.TextBoxWithNormalizedLineBreaks ControlEditPoliticianNickname;
        
        /// <summary>
        /// AsteriskEditPoliticianNickname control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl AsteriskEditPoliticianNickname;
        
        /// <summary>
        /// ControlEditPoliticianLName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vote.TextBoxWithNormalizedLineBreaks ControlEditPoliticianLName;
        
        /// <summary>
        /// AsteriskEditPoliticianLName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl AsteriskEditPoliticianLName;
        
        /// <summary>
        /// ControlEditPoliticianSuffix control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vote.TextBoxWithNormalizedLineBreaks ControlEditPoliticianSuffix;
        
        /// <summary>
        /// AsteriskEditPoliticianSuffix control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl AsteriskEditPoliticianSuffix;
        
        /// <summary>
        /// AddOnEditElement control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl AddOnEditElement;
        
        /// <summary>
        /// ControlEditPoliticianAddOn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vote.TextBoxWithNormalizedLineBreaks ControlEditPoliticianAddOn;
        
        /// <summary>
        /// AsteriskEditPoliticianAddOn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl AsteriskEditPoliticianAddOn;
        
        /// <summary>
        /// ControlEditPoliticianDateOfBirth control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vote.TextBoxWithNormalizedLineBreaks ControlEditPoliticianDateOfBirth;
        
        /// <summary>
        /// AsteriskEditPoliticianDateOfBirth control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl AsteriskEditPoliticianDateOfBirth;
        
        /// <summary>
        /// ControlEditPoliticianStateAddress control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vote.TextBoxWithNormalizedLineBreaks ControlEditPoliticianStateAddress;
        
        /// <summary>
        /// AsteriskEditPoliticianStateAddress control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl AsteriskEditPoliticianStateAddress;
        
        /// <summary>
        /// ControlEditPoliticianStateCityStateZip control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vote.TextBoxWithNormalizedLineBreaks ControlEditPoliticianStateCityStateZip;
        
        /// <summary>
        /// AsteriskEditPoliticianStateCityStateZip control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl AsteriskEditPoliticianStateCityStateZip;
        
        /// <summary>
        /// ControlEditPoliticianStatePhone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vote.TextBoxWithNormalizedLineBreaks ControlEditPoliticianStatePhone;
        
        /// <summary>
        /// AsteriskEditPoliticianStatePhone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl AsteriskEditPoliticianStatePhone;
        
        /// <summary>
        /// ControlEditPoliticianStateEmailAddr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vote.TextBoxWithNormalizedLineBreaks ControlEditPoliticianStateEmailAddr;
        
        /// <summary>
        /// AsteriskEditPoliticianStateEmailAddr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl AsteriskEditPoliticianStateEmailAddr;
        
        /// <summary>
        /// ControlEditPoliticianStateWebAddr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vote.TextBoxWithNormalizedLineBreaks ControlEditPoliticianStateWebAddr;
        
        /// <summary>
        /// AsteriskEditPoliticianStateWebAddr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl AsteriskEditPoliticianStateWebAddr;
        
        /// <summary>
        /// UpdateIntroLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor UpdateIntroLink;
        
        /// <summary>
        /// UpdateIntroLinkProfessional control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor UpdateIntroLinkProfessional;
        
        /// <summary>
        /// ControlEditPoliticianAddress control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vote.TextBoxWithNormalizedLineBreaks ControlEditPoliticianAddress;
        
        /// <summary>
        /// AsteriskEditPoliticianAddress control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl AsteriskEditPoliticianAddress;
        
        /// <summary>
        /// ControlEditPoliticianCityStateZip control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vote.TextBoxWithNormalizedLineBreaks ControlEditPoliticianCityStateZip;
        
        /// <summary>
        /// AsteriskEditPoliticianCityStateZip control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl AsteriskEditPoliticianCityStateZip;
        
        /// <summary>
        /// ControlEditPoliticianPhone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vote.TextBoxWithNormalizedLineBreaks ControlEditPoliticianPhone;
        
        /// <summary>
        /// AsteriskEditPoliticianPhone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl AsteriskEditPoliticianPhone;
        
        /// <summary>
        /// ControlEditPoliticianEmailAddr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vote.TextBoxWithNormalizedLineBreaks ControlEditPoliticianEmailAddr;
        
        /// <summary>
        /// AsteriskEditPoliticianEmailAddr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl AsteriskEditPoliticianEmailAddr;
        
        /// <summary>
        /// ControlEditPoliticianWebAddr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vote.TextBoxWithNormalizedLineBreaks ControlEditPoliticianWebAddr;
        
        /// <summary>
        /// AsteriskEditPoliticianWebAddr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl AsteriskEditPoliticianWebAddr;
        
        /// <summary>
        /// PartyName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl PartyName;
        
        /// <summary>
        /// ControlEditPoliticianPartyKey control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vote.DropDownListWithOptionGroup ControlEditPoliticianPartyKey;
        
        /// <summary>
        /// AsteriskEditPoliticianPartyKey control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl AsteriskEditPoliticianPartyKey;
        
        /// <summary>
        /// FeedbackEditPolitician control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vote.Controls.FeedbackContainerControl FeedbackEditPolitician;
        
        /// <summary>
        /// AjaxLoaderEditPolitician control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image AjaxLoaderEditPolitician;
        
        /// <summary>
        /// ButtonEditPolitician control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ButtonEditPolitician;
        
        /// <summary>
        /// UpdatePanelSetupAd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel UpdatePanelSetupAd;
        
        /// <summary>
        /// ContainerSetupAd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ContainerSetupAd;
        
        /// <summary>
        /// SetupAdReloading control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden SetupAdReloading;
        
        /// <summary>
        /// AdSetupCandidate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden AdSetupCandidate;
        
        /// <summary>
        /// DefaultAdVideo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden DefaultAdVideo;
        
        /// <summary>
        /// UndoSetupAd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl UndoSetupAd;
        
        /// <summary>
        /// SetupAdTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl SetupAdTitle;
        
        /// <summary>
        /// CandidateAdName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl CandidateAdName;
        
        /// <summary>
        /// CandidateAdOffice control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl CandidateAdOffice;
        
        /// <summary>
        /// CandidateAdElection control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl CandidateAdElection;
        
        /// <summary>
        /// CandidateAdRate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl CandidateAdRate;
        
        /// <summary>
        /// AsteriskSetupAdAdType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl AsteriskSetupAdAdType;
        
        /// <summary>
        /// ControlSetupAdAdType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ControlSetupAdAdType;
        
        /// <summary>
        /// ControlSetupAdAdTypeYouTube control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputRadioButton ControlSetupAdAdTypeYouTube;
        
        /// <summary>
        /// ControlSetupAdAdTypeImage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputRadioButton ControlSetupAdAdTypeImage;
        
        /// <summary>
        /// ControlSetupAdAdUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vote.TextBoxWithNormalizedLineBreaks ControlSetupAdAdUrl;
        
        /// <summary>
        /// AsteriskSetupAdAdUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl AsteriskSetupAdAdUrl;
        
        /// <summary>
        /// ControlSetupAdAdThumbnailUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vote.TextBoxWithNormalizedLineBreaks ControlSetupAdAdThumbnailUrl;
        
        /// <summary>
        /// AsteriskSetupAdAdThumbnailUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl AsteriskSetupAdAdThumbnailUrl;
        
        /// <summary>
        /// ControlSetupAdAdImageName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vote.TextBoxWithNormalizedLineBreaks ControlSetupAdAdImageName;
        
        /// <summary>
        /// AsteriskSetupAdAdImageChanged control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl AsteriskSetupAdAdImageChanged;
        
        /// <summary>
        /// ControlSetupAdAdImageChanged control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vote.TextBoxWithNormalizedLineBreaks ControlSetupAdAdImageChanged;
        
        /// <summary>
        /// ControlSetupAdAdImageUpdated control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vote.TextBoxWithNormalizedLineBreaks ControlSetupAdAdImageUpdated;
        
        /// <summary>
        /// ControlSetupAdAdSponsor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vote.TextBoxWithNormalizedLineBreaks ControlSetupAdAdSponsor;
        
        /// <summary>
        /// AsteriskSetupAdAdSponsor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl AsteriskSetupAdAdSponsor;
        
        /// <summary>
        /// ControlSetupAdAdSponsorUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vote.TextBoxWithNormalizedLineBreaks ControlSetupAdAdSponsorUrl;
        
        /// <summary>
        /// AsteriskSetupAdAdSponsorUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl AsteriskSetupAdAdSponsorUrl;
        
        /// <summary>
        /// ControlSetupAdAdIsCandidateSponsored control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputCheckBox ControlSetupAdAdIsCandidateSponsored;
        
        /// <summary>
        /// AsteriskSetupAdAdIsCandidateSponsored control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl AsteriskSetupAdAdIsCandidateSponsored;
        
        /// <summary>
        /// ControlSetupAdAdTimeStamp control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vote.TextBoxWithNormalizedLineBreaks ControlSetupAdAdTimeStamp;
        
        /// <summary>
        /// AsteriskSetupAdAdTimeStamp control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl AsteriskSetupAdAdTimeStamp;
        
        /// <summary>
        /// ControlSetupAdAdEnabled control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputCheckBox ControlSetupAdAdEnabled;
        
        /// <summary>
        /// AsteriskSetupAdAdEnabled control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl AsteriskSetupAdAdEnabled;
        
        /// <summary>
        /// SampleAd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl SampleAd;
        
        /// <summary>
        /// SampleName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl SampleName;
        
        /// <summary>
        /// PaidAdvertisement control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl PaidAdvertisement;
        
        /// <summary>
        /// VideoWrapper control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl VideoWrapper;
        
        /// <summary>
        /// SampleThumb control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlImage SampleThumb;
        
        /// <summary>
        /// ImageWrapper control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ImageWrapper;
        
        /// <summary>
        /// ImageLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor ImageLink;
        
        /// <summary>
        /// AdImage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlImage AdImage;
        
        /// <summary>
        /// SampleProfile control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlImage SampleProfile;
        
        /// <summary>
        /// ComparePageLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor ComparePageLink;
        
        /// <summary>
        /// FeedbackSetupAd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vote.Controls.FeedbackContainerControl FeedbackSetupAd;
        
        /// <summary>
        /// AjaxLoaderSetupAd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image AjaxLoaderSetupAd;
        
        /// <summary>
        /// ButtonSetupAd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ButtonSetupAd;
        
        /// <summary>
        /// UsePoliticianFromListMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl UsePoliticianFromListMessage;
        
        /// <summary>
        /// ContinueAddingNewPoliticianButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputButton ContinueAddingNewPoliticianButton;
        
        /// <summary>
        /// UsePoliticianFromListButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputButton UsePoliticianFromListButton;
        
        /// <summary>
        /// UpdateConsolidate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel UpdateConsolidate;
        
        /// <summary>
        /// ContainerConsolidate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ContainerConsolidate;
        
        /// <summary>
        /// ConsolidateReloading control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden ConsolidateReloading;
        
        /// <summary>
        /// ConsolidateReloaded control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden ConsolidateReloaded;
        
        /// <summary>
        /// ConsolidateKey1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden ConsolidateKey1;
        
        /// <summary>
        /// ConsolidateKey2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden ConsolidateKey2;
        
        /// <summary>
        /// ConsolidateSelectedIndex control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden ConsolidateSelectedIndex;
        
        /// <summary>
        /// ConsolidateSelectedData control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden ConsolidateSelectedData;
        
        /// <summary>
        /// ConsolidateSelectedResponses control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden ConsolidateSelectedResponses;
        
        /// <summary>
        /// ConsolidateItem1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ConsolidateItem1;
        
        /// <summary>
        /// ConsolidateItem2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ConsolidateItem2;
        
        /// <summary>
        /// ConsolidatePersonalTabContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ConsolidatePersonalTabContent;
        
        /// <summary>
        /// ConsolidateContactTabContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ConsolidateContactTabContent;
        
        /// <summary>
        /// ConsolidateWebEmailTabContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ConsolidateWebEmailTabContent;
        
        /// <summary>
        /// ConsolidateSocialTabContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ConsolidateSocialTabContent;
        
        /// <summary>
        /// ConsolidatePicturesTabContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ConsolidatePicturesTabContent;
        
        /// <summary>
        /// ConsolidateAnswersTabContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ConsolidateAnswersTabContent;
        
        /// <summary>
        /// FeedbackConsolidate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vote.Controls.FeedbackContainerControl FeedbackConsolidate;
        
        /// <summary>
        /// AjaxLoaderConsolidate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image AjaxLoaderConsolidate;
        
        /// <summary>
        /// ButtonConsolidate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ButtonConsolidate;
    }
}
